zygo> // define a hashmap with four key-value pairs:
zygo> (def h (hash a:44 b:55 c:77 d:99))
 (hash a:44 b:55 c:77 d:99)
zygo> // define a string to concat stuff to
zygo> (def s "")
""
zygo> // iterate over the hashmap h, adding to s
zygo> (range k v h (set s (concat s " " (str k) "-maps->" (str v) "\n")))
zygo> 
zygo> // inspect the output in s
zygo> s
" a-maps->44\n b-maps->55\n c-maps->77\n d-maps->99\n"
zygo> 